version: '3.4'

services:
  app:
    image: golang:1.17-alpine
    working_dir: /app
    command: go run cmd/main.go
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - jaeger
    volumes:
      - ./:/app
    env_file:
      - config/config.env

  postgres:
    container_name: postgres
    image: postgres:13.4
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data:z
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  jaeger:
    container_name: jaeger_container
    restart: always
    image: jaegertracing/all-in-one:1.35
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"

volumes:
  postgres_data:
    driver: local