version: '3.4'

services:
  server:
    container_name: application
    restart: unless-stopped
    build:
      context: ./
      dockerfile: deployment/docker/Dockerfile
    command: ./app
    depends_on:
      - postgres
    ports:
      - "8000:8000"

  postgres:
    container_name: postgres
    image: postgres:13.4
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data:z
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"